# Hexo Configuration
## Docs: https://.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 楓の葉小窝
subtitle: ''
description: ''
keywords:
author: John Doe
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://linxuesong.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
#不需要渲染的页面
#任务清单页面
skip_render:
- "todolist/**" 
- "friendlink_status/**"

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: false

prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false   # default false
  custom_css:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
#RSS订阅
 plugin:
  hexo-generator-feed
 #Feed Atom
 feed:
   type: atom #RSS的类型(atom/rss2)
   path: atom.xml #文件路径,默认是atom.xml/rss2.xml
   limit: 20 #展示文章的数量,使用0或则false代表展示全部
   hub:
   content: #在RSS文件中是否包含内容 ,有3个值 true/false默认不填为false
   content_limit: 140 #指定内容的长度作为摘要,仅仅在上面content设置为false和没有自定义的描述出现
   content_limit_delim: ' ' #上面截取描述的分隔符,截取内容是以指定的这个分隔符作为截取结束的标志.在达到规定的内容长度之前最后出现的这个分隔符之前的内容,，防止从中间截断.
   order_by: -date
   icon: #icon.png
## Themes: https://hexo.io/themes/
theme: Sakura
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:linxuesong/linxuesong.github.io.git
  branch: master
search:
  path: search.xml
  field: post
  format: html
  limit: 10000  
  
###已弃用，原因Sakura使用了tocbot.js自动生成目录
###已弃用，原因二hexo已内置了toc插件，可以通过修改ejs样式增加，参考https://hexo.io/zh-cn/docs/helpers.html#toc
###toc目录导航插件
#toc:
#  maxdepth: 3
#  class: toc
#  slugify: transliteration
#  decodeEntities: false
#  anchor:
#    position: after
#    symbol: '#'
#    style: header-anchor

  
  #豆瓣账号绑定
douban:
#你的豆瓣 ID
  user: 228541605
#是否将生成页面的功能嵌入 hexo s 和 hexo g 中 为false的话要在启动hexo过程中用hexo douban -bgm
  builtin: true
  # /books为该页面
  book:
  #该页面的标题
    title: 我的书单
    #写在页面开头的一段话，支持 html 语法
    quote: 一个爱书的人，他必定不至于缺少一个忠实的朋友，一个良好的老师，一个可爱的伴侣，一个温情的安慰者。
  movie:
    title: '我的电影'
    quote: '我有喜欢的人，又温暖，又温柔，希望她可以是世界上最幸福的人。为了你，牺牲生命也不足惜。
    <br/>就是这个念头，才能让我忍受痛苦到今天。
    <br/>忍受...
    <br/>忍受到现在。
    <br/>所以我不允许你否定我。
    <br/>“你骗人！”
    <br/>我的的确确有一个喜欢的人，真的有。
    <br/>你以为我是为了谁，又是谁害的。
    <br/>既然都要死，不如就...
    <br/>-------fate/zero雁夜'
  game:
    title: 'This is my game title'
    quote: 'This is my game quote'
  timeout: 10000  
  
  
 #SiteMap 百度谷歌收录
sitemap:
  path: sitemap.xml


bangumi: # 追番设置
  enable: true
  path: bangumi-bilibili/index.html
  vmid: 396134239
  title: '追番列表'
  quote: '生命不息，追番不止！'
  show: 1
  loading:
  metaColor:
  color:
  webp:
  progress:
  extra_options:
    key: value
cinema: # 追剧设置
  enable: true
  path:
  vmid:
  title: '追番列表'
  quote: '生命不息，追番不止！'
  show: 1
  loading:
  metaColor:
  color:
  webp:
  progress:
  extra_options:
    key: value

# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签依赖注入开关
  CDN:
    anima: https://cdn.jsdelivr.net/gh/l-lin/font-awesome-animation/dist/font-awesome-animation.min.css #动画标签anima的依赖
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #issues标签依赖
    issues: https://cdn.jsdelivr.net/npm/hexo-theme-volantis@latest/source/js/issues.min.js #issues标签依赖
    iconfont: //at.alicdn.com/t/font_2032782_8d5kxvn09md.js #参看https://akilar.top/posts/d2ebecef/
    carousel: https://cdn.jsdelivr.net/npm/hexo-butterfly-tag-plugins-plus@latest/lib/carousel-touch.min.js
