# site name
prefixName: 楓の葉
siteName: lean
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/avatar.jpg
url: https://linxuesong.github.io
description: Live your life with passion! With some drive!
cdn: https://cdn.jsdelivr.net/gh/linxuesong/cdn
pjax: 1
# 1开启
mathjax: 0

notice: 博客主题基本确定，接下来时一边写文章一边美化博客了，打算再增加一个记录网站美化记录的页面<br/>评论需要自定义头像的小伙伴请参考https://valine.js.org/avatar.html
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }   #只需要修改fa-XXX  XXX就可以了
  归档: { path: javascript:;, fa: fa-archive faa-shake, submenus: { #图标和图标名 对比地址http://www.fontawesome.com.cn/faicons/
    技术: {path: /categories/技术/, fa: fa-laptop }, #图标css非本地，引用网址上的css文件https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  文章统计: { path: javascript:;, fa: fa-area-chart faa-vertical, submenus: {
    统计: {path: /analytics/, fa: fa-area-chart},
    日历: {path: /archives/, fa: fa-calendar}, 
    标签: {path: /tags/, fa: fa-tag },
    分类: {path: /categories/, fa: fa-bookmark },
    建站日志: {path: /sitelog/, fa: fa-bookmark }
  } }
  
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /books/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones },
    电影: {path: /movies/, fa: fa-video-camera },
    游戏: {path: /games/, fa: fa-gamepad },
    图集: {path: /gallery/, fa: fa-photo },
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    任务清单: {path: /todolist, fa: fa-meetup},
    我？: {path: /about/, fa: fa-meetup}, 
    友链检测: {path: /friendlink_status/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
    娱乐: {path: /dinoswords, fa: fa-coffee },
    客户端: { path: /client/, fa: fa-android faa-vertical }
  } }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 12/12/2018

#social  url, img PC端配置
social:
  github: {url: http://github.com/linxuesong, img: /img/social/github.png}
  csdn: {url: https://blog.csdn.net/lsxa123, img: /img/social/csdn.png}
  cnblog: {url: https://www.cnblogs.com/linxuesong/, img: /img/social/cnblog.jpg}
  wuzhi: {url: https://wuzhi.me/, img: /img/social/wuzhi.png}
  bilibili: {url: https://space.bilibili.com/396134239/video, img: /img/social/bilibili.png}
  qq: {url: https://photo.weibo.com/6504280642/wbphotos/large/mid/4519020298017277/pid/0076biwily1gg2bf3v9wvj30f00kk75n, img: /img/social/qq.png}
  wechat: {url: https://photo.weibo.com/6504280642/wbphotos/large/mid/4519020298017277/pid/0076biwily1gg2bf3v9wvj30f00kk75n, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/honjun, fa: fa-github, color: 333}
  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/donate/AliPayQR.jpg
  wechat: /img/donate/WeChanQR.jpg
  wechatSQ: /img/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4
  


#网易云音乐
#以在sakura\layout\layout.ejs中用明月浩空播放器代替
#aplayer: 
#  id: 2660651585
#  server: netease
#  type: playlist
#  fixed: true
#  autoplay: false
#  loop: all
#  order: random
#  preload: auto
# volume: 0.7
#  mutex: true
#
  
  
  


# Valine
valine: true
v_appId: RmgA0rMeKIWWIkhSTpqhV4oG-gzGzoHsz
v_appKey: iwivlkfT6bGJRQS74SaKYjal



# Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: true
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
 
 # Whether to activate the copyright information of the blog and author when copying the post content.
# minCharNumber: Approve copyright information by copying at least how many characters.
# 是否激活复制文章时追加博客和作者的版权信息.
copyright:
  enable: false
  minCharNumber: 120 # 至少复制多少个字符就追加版权信息.
  description: 本文章著作权归作者所有，任何形式的转载都请注明出处。

# 代码块相关
code:
  lang: true # 代码块是否显示名称
  copy: true # 代码块是否可复制
  shrink: true # 代码块是否可以收缩
  break: true # 代码是否折行

# 查看大图
fancybox:
  enable: true

# 外链转知乎卡片形式 
linkcard:
  enable: true 

# 是否开启字数统计 (可以在formatton设置no_word_count: true)
#不需要使用，直接设置值为false，或注释掉
post_wordcount:
  item_text: true
  wordcount: true
  min2read: true
  totalcount: true
  separated_meta: true   
 
# busuanzi(http://busuanzi.ibruce.info/) website statistics
# 不蒜子(http://busuanzi.ibruce.info/) 网站统计
busuanziStatistics:
  enable: true
  totalTraffic: true # 总访问量
  totalNumberOfvisitors: true # 总人次
  
# rss地址
rss: /atom.xml
# Online contact ##在线聊天 https://www.daovoice.io/
daovoice:
  enable: true
  daovoice_app_id: 7e5676fe ##这里替换成你DaoVoice上的appid

# Whether to display post-calender in the `archive` page
# 设置在归档页面achive中是否显示'文章日历'控件
postCalendar: true 


# 增加了相册页面 
gallery: 
  title: 光影流年 #标题 
  icon: fa #这个显示相册页面的图标 
  icon2: fa #这个显示自己的具体相册里面的相册的图标
PhotoVerifyPassword: 
  enable: true 
  promptMessage: 该相册已加密，请输入密码访问 
  errorMessage: 密码错误，将返回主页！


#------------------------CDN,非必要--------------------------
libs:
  css:
    baguetteBoxCss: https://nekodeng.gitee.io/libs/MyGallery/css/baguetteBox.css
    googlefonts: https://fonts.googleapis.com/css?family=Noto+SerifMerriweather|Merriweather+Sans|Source+Code+Pro|Ubuntu:400,700|Noto+Serif+SC
    style: https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/style.css #/css/style.css # 
    lib: https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/lib.min.css
    font: https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/font.css
    insight: /css/insight.css
    tags: https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/tags.css
    fancybox: https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/jquery.fancybox.min.css
    sharejs: https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/sharejs.css
    tocbot: https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.4.2/tocbot.css
    live2d_widget: https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css
    logo:
      enable: true # 自定义logo
      logo: https://cdn.jsdelivr.net/gh/cungudafa/cdn/css/logo.css
      logo_fonts: https://cdn.jsdelivr.net/gh/cungudafa/cdn/fonts/LOGO/logo.css
  js:
    jquery: https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
    linkcard: /js/linkcard.js
    lib: https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/lib.min.js
    clipboard: https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
    InsightSearch: https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/InsightSearch.js
    sakura_app: https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/sakura-app.js  #/js/sakura-app.js
    busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js 
    fancybox: https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/jquery.fancybox.min.js
    echarts: https://cdn.jsdelivr.net/gh/cungudafa/cdn/js/echarts.min.js
    valine: https://unpkg.com/valine/dist/Valine.min.js
    sakura_petal: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/sakura.js #other
    hititle: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/hititle.js 
    KeyBlock: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/noSomeKey.js #按键屏蔽,不能F12调试和查看源代码
    sakura_petals: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/sakura.js  #仅在首页花瓣飘落（大内存）
    snow_petals: https://cdn.jsdelivr.net/gh/Yafine/cdn@2.5/source/js/snow1.js
    piao: https://cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/piao.js #飘动彩带
    live2d_widget: https://cdn.jsdelivr.net/gh/cungudafa/cdn/live2d-widget/autoload.js
    word: https://cdn.jsdelivr.net/gh/wallleap/cdn/js/shehuizhuyi.js #点击出现字效
    love: https://cdn.jsdelivr.net/gh/wallleap/cdn/js/love.js #点击出现爱心
    cursor: https://cdn.jsdelivr.net/gh/cungudafa/cdn@2.1.2/js/cursor.js # 星星跟随坠落(大内存)
    baguetteBoxJs: https://nekodeng.gitee.io/libs/MyGallery/js/baguetteBox.js